### ISSUE TITLE
Empty P tag at the after the short code. 

### ISSUE THREAD

**Issue by rgfx** [chiedolabs/shortcode-wpautop-control#1]
Thanks for the plugin, anyhow.

.I made a short-code to add html inside the editor, Getting a empty p tag at the end of my shortcode 

```
//function 

function html_func( $atts, $content = null ){
  return $content;
}
add_shortcode( 'html', 'html_func' );

/// My content code 

[html]
<div>test</div>
[/html]

/// output

<div>test</div>
<p></p>

```

Thanks

**Comment by chiedo** [comment]
Hey @rgfx, There's nothing you can do that I'm awarae of to stop the p tags from coming before or after your shortcode. 

In your case, the p tags are after your shortcodes, not in them. This plugin can only make sure no p tags occur inside your shortcode.

For example, if you modify your script to this:
```
function html_func( $atts, $content = null ){
  return "<pre>$content</pre>";
}
```

You'll get this output
```
<pre>
<div>test</div>
</pre>
<p></p>
```

That lets you know that the p tags are not in your shortcode but outside of the shortcode content.

Make sense?

**Comment by rgfx** [comment]
Yes that makes sense, However if I disable your plugin. The empty p tag doesn't get generated.

**Comment by chiedo** [comment]
That make sense. I'm not surprised that my script conflicts with other haha. Want to submit a pull request with the fix?
